---
title: "ESS analysis"
author: "Bose Falk"
output:
  html_document:
    df_print: paged
---

# Data loading

```{r}
library(lavaan)
library(ggplot2)
library(tidyverse)
source('lib/loading_scripts.R')

dat <- load_data('trustdem2', open_docs = FALSE)
#validate_data(dat) # Haven't finished updating validation rules for new variables

dat %<>% rename(trust_legal = trstlgl, 
          trust_polparties = trstprt, 
          trust_police = trstplc, 
          trust_parliament = trstprl, 
          tv_polnews = tvpol, 
          radio_polnews = rdpol, 
          newsp_polnews = nwsppol, 
          ppl_trustworthy = ppltrst, 
          ppl_fair = pplfair, 
          ppl_helpful = pplhlp, 
          income = hinctnta, 
          age = agea)
```


## SEM model specification


```{r}

# Background on SEM modelling in R:
# http://lavaan.ugent.be/tutorial/tutorial.pdf
# http://joophox.net/publist/semfamre.pdf
# http://m-clark.github.io/docs/sem/structural-equation-modeling.html#measurement-model

SEM_model <- 'trust_gov =~ trust_parliament + trust_legal + trust_police + trust_polparties
  trust_ind =~ ppl_trustworthy + ppl_fair + ppl_helpful
  pol_news =~ tv_polnews + radio_polnews + newsp_polnews
  trust_gov ~ trust_ind + pol_news + netuse + income + age

  # Individual trust and news watching is not correlated
  trust_ind ~~ 0*pol_news


  # Correlations
  age ~~ netuse + income
'
```

## Fitting models
```{r}
# Create dataframes with individual model data based on country and study round

dat_DK4 <- dat %>% filter(essround == "4" & cntry == "DK")
dat_DK5 <- dat %>% filter(essround == "5" & cntry == "DK")

dat_EE4 <- dat %>% filter(essround == "4" & cntry == "EE")
dat_EE5 <- dat %>% filter(essround == "5" & cntry == "EE")

dat_CZ4 <- dat %>% filter(essround == "4" & cntry == "CZ")
dat_CZ5 <- dat %>% filter(essround == "5" & cntry == "CZ")

```

### Small example model

```{r}
SEM_basic <- 'trust_gov =~ trust_parliament + trust_legal + trust_police + trust_polparties
  pol_news =~ tv_polnews + radio_polnews + newsp_polnews
  trust_gov ~ pol_news + netuse

'

fit_basic <- sem(SEM_basic, data = dat_DK4)
summary(fit_basic)

```

### Fit all 6 models


```{r}
fit_DK4 <- sem(SEM_model, data = dat_DK4)
fit_DK5 <- sem(SEM_model, data = dat_DK5)

fit_EE4 <- sem(SEM_model, data = dat_EE4)
fit_EE5 <- sem(SEM_model, data = dat_EE5)

fit_CZ4 <- sem(SEM_model, data = dat_CZ4)
fit_CZ5 <- sem(SEM_model, data = dat_CZ5)

```

# Result plots

```{r}
list_of_fits <- list("DK4" = fit_DK4, "DK5" = fit_DK5, 
                     "EE4" = fit_EE4, "EE5" = fit_EE5, 
                     "CZ4" = fit_CZ4, "CZ5" = fit_CZ5)

colour_scale = scale_colour_manual(values = c("DK4" = "green", "DK5" = "darkgreen", 
                                 "EE4" = "blue", "EE5" = "darkblue", 
                                 "CZ4" = "red", "CZ5" = "darkred"))

```

### Coefficient estimates

```{r}
params_list <- list()
for (i in 1:length(list_of_fits)) {
  params_list[[i]] <- parameterEstimates(list_of_fits[[i]])
  params_list[[i]]$source <- names(list_of_fits)[i]
  
}

params_df <- do.call(rbind, params_list)
params_df %<>% filter(lhs == 'trust_gov' & op == '~') %>% select(rhs, est, ci.lower, ci.upper, source)

ggplot(params_df, aes(x = rhs)) + 
  geom_pointrange(aes(y = est, ymin = ci.lower, ymax = ci.upper, colour = source), position=position_dodge(width=0.4)) + 
  geom_hline(yintercept = 0) +
  colour_scale +
  labs(title = "Coefficient Estimates", 
       x = "Variable", 
       y = "Estimate")


```

### RMSEA diagnostic

```{r}


fit_out_list <- list()
for (i in 1:length(list_of_fits)) {
  fit_out <- fitmeasures(list_of_fits[[i]])
  fit_out_list[[i]] <- data.frame(source = names(list_of_fits)[i], 
                       rmsea = fit_out['rmsea'], 
                       rmsea.ci.lower = fit_out['rmsea.ci.lower'], 
                       rmsea.ci.upper = fit_out['rmsea.ci.upper'])

}
fit_df <- do.call(rbind, fit_out_list)

ggplot(fit_df, aes(x = source)) + geom_pointrange(aes(y = rmsea, ymin = rmsea.ci.lower, ymax = rmsea.ci.upper, colour = source)) +
  colour_scale +
  expand_limits(y = 0) +
  geom_hline(yintercept = 0.1, lty = 3) +
  geom_hline(yintercept = 0.05, lty = 2) +
  geom_hline(yintercept = 0) +
  labs(title = "Root Mean Square Error of Approximation", 
       x = "Model", 
       y = "RMSEA")

```

